### ISSUE TITLE
GNS3

### ISSUE THREAD

**Issue by titouan-joseph** [TCastus/TChelp#1]
Faire la presentation de GNS3 
Configuration de base

**Comment by titouan-joseph** [comment]
@Phoross tu peux relire cette partie je pense

**Comment by Phoross** [comment]
J'ai relu et corrigé deux trois trucs.
Pour l'utilisation serveur et VM je sais pas si ca vaut le coup de le faire vu qu'on l'utilise pas. A la limite on peut mettre un lien vers des ressources mais pas sur que ca vaille le coup de prendre le temps et d'expliquer.

**Comment by titouan-joseph** [comment]
okay merci bien
je vais regarder de trouver une ressource la-dessus
