### ISSUE TITLE
Discord tutorial 

### ISSUE THREAD

**Issue by aprouvost** [TCastus/TChelp#11]

**Comment by titouan-joseph** [comment]
Je regarde de faire le model serveur

**Comment by aprouvost** [comment]
Je prends la partie "création d'un serveur", je fais ça dans la journée/ demain si nécessaire

**Comment by titouan-joseph** [comment]
Je viens de mettre quelque utilisation basique dans la presentation

**Comment by aprouvost** [comment]
Partie "création d'un serveur terminée", en attente de relecture (sous 24h)

**Comment by Phoross** [comment]
J'ai relu l'article création de serveur et j'ai juste corriger deux trois typos

**Comment by titouan-joseph** [comment]
Tu peux relire le reste aussi normalement c'est fini

**Comment by Phoross** [comment]
Je viens de relire tout les articles Discord et de corriger

**Comment by titouan-joseph** [comment]
TODO: mettre a jour la doc du serveur model
