### ISSUE TITLE
Tuto Spyder

### ISSUE THREAD

**Issue by clementlagneau** [TCastus/TChelp#13]

**Comment by Lgt2x** [comment]
C'est un soft utilisé en 4TC @titouan-joseph  ? jamais entendu parler

**Comment by titouan-joseph** [comment]
Nop c'est un ide pour python

**Comment by Lgt2x** [comment]
dac, c'est peut-être pas le plus utlisé, il vaut mieux recommander Pycharm qui devient un peu le standard à mon avis

**Comment by titouan-joseph** [comment]
Ça peut valoir le coup de le présenter rapidement dans la section ide mais peut-être pas la peine de faire une présentation aussi poussé que pycharm ou vs code

**Comment by titouan-joseph** [comment]
Je pense on peut fermer l'issue
On a déjà une présentation ici IDE/Spyder/presentation.md
