### ISSUE TITLE
Tuto WSL

### ISSUE THREAD

**Issue by titouan-joseph** [TCastus/TChelp#9]
Presentation de WSL puis installation
Lien a mettre dans terminal section windows

**Comment by titouan-joseph** [comment]
Update WSL 2 : https://docs.microsoft.com/fr-fr/windows/wsl/install-win10
Installation du GUI : https://eecs.blog/wsl-gui-installation-for-kali-linux/

**Comment by titouan-joseph** [comment]
Faire tuto xfce
+ tuto avec un serveur X pour avoir les fenetre directement dans windows
 - [ ] installation -> https://doc.ubuntu-fr.org/wsl#installer_un_serveur_x
 - [ ] Firewall -> https://stackoverflow.com/questions/61860208/wsl-2-run-graphical-linux-desktop-applications-from-windows-10-bash-shell-erro

**Comment by Lgt2x** [comment]
> Faire tuto xfce
> 
>     * tuto avec un serveur X pour avoir les fenetre directement dans windows
> 
> 
>     * [ ]  installation -> https://doc.ubuntu-fr.org/wsl#installer_un_serveur_x
> 
>     * [ ]  Firewall -> https://stackoverflow.com/questions/61860208/wsl-2-run-graphical-linux-desktop-applications-from-windows-10-bash-shell-erro

@thomslor tu te sentirais de regarder ça ? J'y connais R

**Comment by thomslor** [comment]
Euh je peux essayer de regarder ca

**Comment by Lgt2x** [comment]
> Euh je peux essayer de regarder ca

le goat

**Comment by thomslor** [comment]
J'ai essayé un peu ce soir et ca ne marche pas pour l'instant. Ca a l'air quand même d'être une sacré machine à gaz pour pas grand chose tout de même

**Comment by thomslor** [comment]
Hello @titouan-joseph, j'ai ouvert une petite PR pour la partie Serveur X, j'ai réussi à débug mon installation (ca reste peu fiable quand même, WSLg va arriver comme le Messi)

**Comment by titouan-joseph** [comment]
Je regarde ça 😉
